#!/usr/bin/env bash
# Local dev bootstrap — Postgres user/db, backend .env, deps, migrations.
# Run from repo root: bash scripts/setup-local-env.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND="$REPO_ROOT/backend"
FRONTEND="$REPO_ROOT/frontend"

DB_USER="${HRMS_DB_USER:-hrms}"
DB_PASS="${HRMS_DB_PASS:-hrms_local_dev}"
DB_NAME="${HRMS_DB_NAME:-hrms}"
DB_HOST="${HRMS_DB_HOST:-localhost}"
DB_PORT="${HRMS_DB_PORT:-5432}"

echo "── HRMS local environment setup ──"

if ! command -v psql >/dev/null 2>&1; then
  echo "✖ psql not found. Install PostgreSQL 16+ (docs/14: native Postgres, no Docker)." >&2
  exit 1
fi

if ! pg_isready -h "$DB_HOST" -p "$DB_PORT" >/dev/null 2>&1; then
  echo "✖ PostgreSQL not accepting connections on $DB_HOST:$DB_PORT" >&2
  echo "  Start Postgres (e.g. brew services start postgresql@16) and retry." >&2
  exit 1
fi

echo "── Ensuring database role and database exist…"
psql -h "$DB_HOST" -p "$DB_PORT" -d postgres -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}';
  END IF;
END
\$\$;
SQL

if ! psql -h "$DB_HOST" -p "$DB_PORT" -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
  psql -h "$DB_HOST" -p "$DB_PORT" -d postgres -v ON_ERROR_STOP=1 -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"
  echo "  Created database ${DB_NAME}"
else
  echo "  Database ${DB_NAME} already exists"
fi

psql -h "$DB_HOST" -p "$DB_PORT" -d "$DB_NAME" -v ON_ERROR_STOP=1 -c "GRANT ALL ON SCHEMA public TO ${DB_USER};" 2>/dev/null || true

ENV_FILE="$BACKEND/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-local-env.sh — do not commit
NODE_ENV=development
PORT=5100
LOG_LEVEL=info
DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
EOF
  echo "── Wrote $ENV_FILE"
else
  echo "── $ENV_FILE already exists (not overwritten)"
fi

if [[ ! -f "$FRONTEND/.env" ]] && [[ -f "$FRONTEND/.env.example" ]]; then
  cp "$FRONTEND/.env.example" "$FRONTEND/.env"
  echo "── Wrote frontend/.env from .env.example"
fi

echo "── Backend: npm install + migrate…"
cd "$BACKEND"
npm install
export DATABASE_URL="postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
npm run migrate

echo "── Frontend: npm install…"
cd "$FRONTEND"
npm install

echo ""
echo "✔ Local env ready."
echo ""
echo "  Terminal 1: cd backend && npm run dev    # http://localhost:5100/health"
echo "  Terminal 2: cd frontend && npm run dev # http://localhost:5173"
echo ""
echo "  Verify:     cd backend && npm run verify"
echo "              cd frontend && npm run verify"
